### ISSUE TITLE
build gradle的时候报错 

### ISSUE THREAD

**Issue by 347649749xzh** [jiangkang/KTools#2]
Error:(4, 0) F:\webDemo\KTools\kflutter\.android\include_flutter.groovy (F:\webDemo\KTools\kflutter\.android\include_flutter.groovy)
<a href="openFile:F:\webDemo\KTools\settings.gradle">Open File</a>

**Comment by jiangkang** [comment]
这个项目加入了flutter，需要本地配置下flutter环境
